### PR TITLE
Hardcode Institutions on the map

### PR DESCRIPTION
**Pull request by jzhang005**
The location of institutions is now hardcoded on the map as markers. To view the map, go to Home and click Map to view the map. InfoWindow will be added later.

### CODE REVIEW

**Comment by ian-s-mcb** [comment]
@jzhang005 A couple comments on your PR:

- You installed both the google-map and google-maps react libraries
- You committed your API access key
- You placed the map on it's own page, but we want it on the indexpage

**Comment by ian-s-mcb** [comment]
I'm reading about sorting secrets outside of a repo here: https://docs.aws.amazon.com/amplify/latest/userguide/environment-variables.html

**Comment by TadjM** [comment]
Hi Jin you should put the map on the homepage where you have the sign in and signup links

**Comment by ian-s-mcb** [comment]
#46 contains the corrections to this PR, so review/merge that one instead of this one.

**Pull request closed without merging**
